CREATE DATABASE bycoders;
\c bycoders;

CREATE TABLE IF NOT EXISTS donos(
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(14) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS lojas(
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(19) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS transacoes(
    id SERIAL PRIMARY KEY,
    tipo VARCHAR(22) NOT NULL,
    data DATE NOT NULL,
    valor FLOAT NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    cartao VARCHAR(12) NOT NULL,
    hora TIME NOT NULL,
    id_dono INTEGER NOT NULL REFERENCES donos(id),
    id_loja INTEGER NOT NULL UNIQUE REFERENCES lojas(id)
);
